export const DYNAMODB_ATTRIBUTES = {
  userId: 'userId',
  roomId: 'roomId',
  hostUserId: 'hostUserId',
  inviteCode: 'inviteCode',
  connectionId: 'connectionId',
  sentAtMessageId: 'sentAtMessageId',
  sequence: 'sequence',
  occurredAtReactionId: 'occurredAtReactionId',
  scheduledPartyId: 'scheduledPartyId',
  eventId: 'eventId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  joinedAt: 'joinedAt',
  sentAt: 'sentAt',
  lastSeenAt: 'lastSeenAt',
  expiresAt: 'expiresAt',
  visibilityStatus: 'visibilityStatus',
  emailLower: 'emailLower',
} as const;
